module "aws_podcast" {
  source              = "../../modules/aws_podcast"
  category_one        = var.category_one
  category_two        = var.category_two
  content_bucket_name = var.content_bucket_name
  content_domain_name = var.content_domain_name
  copyright_text      = var.copyright_text
  domain_name         = var.domain_name
  explicit            = var.explicit
  log_bucket_name     = var.log_bucket_name
  podcast_author      = var.podcast_author
  podcast_description = var.podcast_description
  podcast_email       = var.podcast_email
  podcast_file_name   = var.podcast_file_name
  podcast_language    = var.podcast_language
  podcast_name        = var.podcast_name
  podcast_subtitle    = var.podcast_subtitle
  podcast_type        = var.podcast_type
  rss_bucket_name     = var.rss_bucket_name
  rss_domain_name     = var.rss_domain_name
  subcategory_one     = var.subcategory_one
  subcategory_two     = var.subcategory_two
}
