module "aws_podcast" {
  source = "../../modules/aws_podcast"
  category_one = "Technology"
  category_two = "Technology"
  content_bucket_name = "podcast-content-bucket-mike"
  content_domain_name = "podcastcontent.michaelgoehle.com"
  copyright_text = "© Michael Goehle 2022"
  domain_name = "michaelgoehle.com"
  explicit = "false"
  log_bucket_name = "podcast-log-bucket-mike"
  podcast_author = "Michael Goehle"
  podcast_description = "This is how a podcast gets made"
  podcast_email = "me@michaelgoehle.com"
  podcast_file_name = "podcast.xml"
  podcast_language = "en-us"
  podcast_name = "Mike G's opensource podcast podcast"
  podcast_subtitle = "An example of a podcast"
  podcast_type = "episodic"
  rss_bucket_name = "podcast-rss-bucket-mike"
  rss_domain_name = "podcast.michaelgoehle.com"
  subcategory_one = "Technology"
  subcategory_two = "Technology"
}
